<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- qtconcurrentexception.cpp -->
<head>
  <title>Qt 4.6: Exception Class Reference</title>
  <link href="classic.css" rel="stylesheet" type="text/css" />
</head>
<body>
<a name="//apple_ref/cpp/cl/QtConcurrent/Exception"></a>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td align="left" valign="top" width="32"><a href="http://qt.nokia.com/"><img src="images/qt-logo.png" align="left" border="0" /></a></td>
<td width="1">&nbsp;&nbsp;</td><td class="postheader" valign="center"><a href="index.html"><font color="#004faf">Home</font></a>&nbsp;&middot; <a href="classes.html"><font color="#004faf">All&nbsp;Classes</font></a>&nbsp;&middot; <a href="functions.html"><font color="#004faf">All&nbsp;Functions</font></a>&nbsp;&middot; <a href="overviews.html"><font color="#004faf">Overviews</font></a></td></tr></table><h1 class="title">Exception Class Reference<br /><span class="small-subtitle">(QtConcurrent::Exception)<br />[<a href="qtcore.html">QtCore</a> module]</span>
</h1>
<p>The Exception class provides a base class for exceptions that can transferred across threads. <a href="#details">More...</a></p>
<p>Inherited by <a href="qtconcurrent-unhandledexception.html">QtConcurrent::UnhandledException</a>.</p>
<p>This class was introduced in Qt 4.4.</p>
<ul>
<li><a href="qtconcurrent-exception-members.html">List of all members, including inherited members</a></li>
</ul>
<hr />
<a name="public-functions"></a>
<h2>Public Functions</h2>
<table class="alignedsummary" border="0" cellpadding="0" cellspacing="0" width="100%">
<tr><td class="memItemLeft" align="right" valign="top">virtual Exception * </td><td class="memItemRight" valign="bottom"><b><a href="qtconcurrent-exception.html#clone">clone</a></b> () const</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual void </td><td class="memItemRight" valign="bottom"><b><a href="qtconcurrent-exception.html#raise">raise</a></b> () const</td></tr>
</table>
<a name="details"></a>
<hr />
<h2>Detailed Description</h2>
<p>The Exception class provides a base class for exceptions that can transferred across threads.</p>
<p>Qt Concurrent supports throwing and catching exceptions across thread boundaries, provided that the exception inherit from QtConcurrent::Exception and implement two helper functions:</p>
<pre> class MyException : public QtConcurrent::Exception
 {
 public:
     void raise() const { throw *this; }
     Exception *clone() const { return new MyException(*this); }
 };</pre>
<p>QtConcurrent::Exception subclasses must be thrown by value and caught by reference:</p>
<pre> try  {
     QtConcurrent::blockingMap(list, throwFunction); <span class="comment">// throwFunction throws MyException</span>
 } catch (MyException &amp;e) {
     <span class="comment">// handle exception</span>
 }</pre>
<p>If you throw an exception that is not a subclass of QtConcurrent::Exception, the Qt Concurrent functions will throw a <a href="qtconcurrent-unhandledexception.html">QtConcurrent::UnhandledException</a> in the receiver thread.</p>
<p>When using <a href="qfuture.html">QFuture</a>, transferred exceptions willl be thrown when calling the following functions:</p>
<ul>
<li><a href="qfuture.html#waitForFinished">QFuture::waitForFinished</a>()</li>
<li><a href="qfuture.html#result">QFuture::result</a>()</li>
<li><a href="qfuture.html#resultAt">QFuture::resultAt</a>()</li>
<li><a href="qfuture.html#results">QFuture::results</a>()</li>
</ul>
<hr />
<h2>Member Function Documentation</h2>
<a name="//apple_ref/cpp/instm/QtConcurrent::Exception/clone"></a>
<h3 class="fn"><a name="clone"></a>Exception * Exception::clone () const&nbsp;&nbsp;<tt> [virtual]</tt></h3>
<p>In your <a href="qtconcurrent-exception.html">QtConcurrent::Exception</a> subclass, reimplement clone() like this:</p>
<pre> MyException *MyException::clone() const { return new MyException(*this); }</pre>
<a name="//apple_ref/cpp/instm/QtConcurrent::Exception/raise"></a>
<h3 class="fn"><a name="raise"></a>void Exception::raise () const&nbsp;&nbsp;<tt> [virtual]</tt></h3>
<p>In your <a href="qtconcurrent-exception.html">QtConcurrent::Exception</a> subclass, reimplement raise() like this:</p>
<pre> void MyException::raise() const { throw *this; }</pre>
<p /><address><hr /><div align="center">
<table width="100%" cellspacing="0" border="0"><tr class="address">
<td width="40%" align="left">Copyright &copy; 2010 Nokia Corporation and/or its subsidiary(-ies)</td>
<td width="20%" align="center"><a href="trademarks.html">Trademarks</a></td>
<td width="40%" align="right"><div align="right">Qt 4.6.2</div></td>
</tr></table></div></address></body>
</html>
